### ISSUE TITLE
is it possible to add MARKET/OPG orders?

### ISSUE THREAD

**Issue by marcoslopez1122** [MaxxRK/firstrade-api#16]
Hello. Thank you for the project. I am new with GitHub, not sure this is the right place to suggest adding the possibility of trading MARKET with Instructions=OPG.  Regards.

**Edited**: I have edited the HTML and it seems that adding qualifier = 4 should make it trade OPG, however I cannot make it work. It doesn't send the order although I have a "Order Placed Successfully" message. OrderID = preview_warning

**Comment by MaxxRK** [comment]
I will look at this when I get some time. I have been quite busy. If I can get the codes correct it is definitely possible to add.

**Comment by MaxxRK** [comment]
This is now added in the firstrade-api v0.0.21 release.

**Comment by marcoslopez1122** [comment]
I appreciate it. Thank you very much))))
