### ISSUE TITLE
More information of position

### ISSUE THREAD

**Issue by sstarlung** [MaxxRK/firstrade-api#25]
Is it possible add 'Market Value', 'Unit Cost', 'Total Cost', etc. into position information? Thank you.

**Comment by MaxxRK** [comment]
I looked through the response from a quote today and I do not see a specific field that has 'Market Value', 'Unit Cost', or 'Total Cost'. Is this something that would be part of holdings you already own, or a symbol quote? 

I did go back and add every entry that it returns to a symbol quote now.

**Comment by sstarlung** [comment]
Oh! I just saw these columns on website. It turns out it wasn’t captured from a webpage! I misunderstood. Thank you.

**Comment by MaxxRK** [comment]
Closing this issue it seems resolved.
