### ISSUE TITLE
Place Option Order

### ISSUE THREAD

**Issue by sstarlung** [MaxxRK/firstrade-api#29]
Is it possible to support option order? Following is my example of a option order:

> submiturl: /cgi-bin/optionorder_request
orderbar_clordid: 
orderbar_accountid: 
optionorderpage: yes
submitOrders: 
previewOrders: 1
lotMethod: 1
accountType: 2
quoteprice: 
viewederror: 
stocksubmittedcompanyname1: 
opt_choice: SO
accountId: 12345678
transactionType: BO
contracts: 1
underlyingsymbol: TSLA
expdate: 06/07/2024
strike: 170.000
callputtype: P
priceType: 3
stopPrice: 3.5
duration: 0
qualifier: 
cond_symbol0_0: 
cond_type0_0: 2
cond_compare_type0_0: 2
cond_compare_value0_0: 
cond_and_or0: 1
cond_symbol0_1: 
cond_type0_1: 2
cond_compare_type0_1: 2
cond_compare_value0_1: 
optionspos_dropdown1: 
transactionType2: 
contracts2: 
underlyingsymbol2: 
expdate2: 
strike2: 
optionspos_dropdown2: 
transactionType3: 
contracts3: 
underlyingsymbol3: 
expdate3: 
strike3: 
netprice_sp: 
qualifier_sp: 
optionspos_dropdown3: 
transactionType4: 
contracts4: 
underlyingsymbol4: 
expdate4: 
strike4: 
transactionType5: 
contracts5: 
underlyingsymbol5: 
expdate5: 
strike5: 
netprice_st: 
qualifier_st: 
optionspos_dropdown: 
contracts10: 
expdate11: 
strike11: 
netprice_ro: 
qualifier_ro: 
opt_u_symbol: 
mleg_close_dropdown: 
transactionType6: 
contracts6: 
underlyingsymbol6: 
expdate6: 
strike6: 
callputtype6: P
transactionType7: 
contracts7: 
underlyingsymbol7: 
expdate7: 
strike7: 
callputtype7: P
transactionType8: 
contracts8: 
underlyingsymbol8: 
expdate8: 
strike8: 
callputtype8: P
transactionType9: 
contracts9: 
underlyingsymbol9: 
expdate9: 
strike9: 
callputtype9: P
netprice_bf: 
qualifier_bf:

**Comment by MaxxRK** [comment]
This is being worked on in the "options" branch.

**Comment by MaxxRK** [comment]
This has been added in this release. https://github.com/MaxxRK/firstrade-api/releases/tag/v_0030

I will leave this issue open for a little while longer as I am not an advanced trader and do not trade options very much/at all. Please let me know if you encounter any problems and I will work to get them fixed.

Thanks and enjoy!

**Comment by MaxxRK** [comment]
Have you tried to use this for option orders?

**Comment by MaxxRK** [comment]
closing this there has been no response
