### ISSUE TITLE
Login failed. Check your credentials.

### ISSUE THREAD

**Issue by nb7123** [MaxxRK/firstrade-api#31]
First, that's great!

When i run test.py use my account like:
ft_ss = account.FTSession(username="my_account", password="my_passwd", pin="MMyy") 
python3 test.py

I got the error: Login failed. Check your credentials.

I searched firstrade website, it says the 'pin' is my birthday month and year.

Can anyone tell me where is it wrong?

thank you very much ^_^

**Comment by nb7123** [comment]
Now i know about the 'pin' meaning, is it the verify code?
If it is, the login logic cann't auto request the pin, how to solve this problem?
and when i handle login with a web browser and request a pin but:
response = self.session.post(
                url=urls.pin(), headers=headers, cookies=self.session.cookies, data=data
            )
  
this call return: {"success": false, "error_code": 1210,"error": "Invalid PIN"}

where am i wrong?

thank you!

**Comment by MaxxRK** [comment]
The pin is a login code set by the user. Firstrade used to only have this option it is not a traditional totp. It can usually be setup in the profile settings and when you go to login instead of using an authenticator or a phone code click the option to "Use another method" it should ask for a pin.

**Comment by nb7123** [comment]
thank you very much, i'll try again

**Comment by nb7123** [comment]
Just close it
