### ISSUE TITLE
illiquid stock error

### ISSUE THREAD

**Issue by arisshu** [MaxxRK/firstrade-api#32]
When trading illiquid stock, order_confirmation return success code but order will not place.

`{'success': 'Yes', 'Transaction': 'Buy', 'Shares': '1', 'Symbol': '***', 'Price': 'Limit at ***', 'Duration': 'DAY', 'Instruction': '', 'Est. Commission': '$0.00', 'Est. Total': '$***', 'orderid': 'tyle="width:100%;margin:10pt 
0pt;padding:0pt;display:block">\n\t<div class="yellow box"  style="width:99.5%;margin: 0pt;padding: 0pt;">\n\t\t<div class="error_msg" id="preview_warning" style="height:100%;width:100%;margin:4pt 0pt;padding:0pt;" >\n\t\t<div class="outbox">\n\t\t<div class="inbox" style="width:100%;height:100%" ><span  style="width:98%;height:100%;margin:0px 10px;line-height: 140%" >NOTE: You are trading an illiquid stock, excessive trading may trigger order rejects. If confirmed, click on &quot;send order&quot; again. </span>', 'errcode': '1000'}`

Upon manualling placing order this red box pop up on specific ticker
![IMG_6722](https://github.com/user-attachments/assets/94b21f80-0bb4-49f0-95d4-b586cea61ee9)

Any fix that can be done here?

**Comment by MaxxRK** [comment]
The newest release will submit the order if it sees a warning, and add it to the order_cofirmation dictionary `order_confirmation['warning']`

i.e.  `{'warning': 'NOTE: You are trading an illiquid stock, excessive trading may trigger order rejects. If confirmed, click on "send order" again.', 'success': 'Yes', 'Transaction': 'Buy', 'Shares': '1', 'Symbol': 'LUCY', 'Price': 'Limit at 0.44', 'Duration': 'DAY', 'Instruction': '', 'Est. Commission': '$0.00', 'Est. Total': '$0.44', 'orderid': '11111111-111', 'errcode': '1000'}`
