### ISSUE TITLE
Is there any apis to query History orders?

### ISSUE THREAD

**Issue by nb7123** [MaxxRK/firstrade-api#39]
Is there any apis to query History orders?

**Comment by MaxxRK** [comment]
There is a method to get order status are you asking for one that gets older order history?

**Comment by nb7123** [comment]
> There is a method to get order status are you asking for one that gets older order history?

yes，i want get older order history.

**Comment by MaxxRK** [comment]
I am working on adding a few things in a big update. This will be in it. I
estimate a couple of weeks before it is out.

**Comment by MaxxRK** [comment]
This feature has been added in this release. https://github.com/MaxxRK/firstrade-api/releases/tag/v_0030

Enjoy!

**Comment by nb7123** [comment]
Thank you very much. ^_^
