### ISSUE TITLE
https://api3x.firstrade.com/sess/login

### ISSUE THREAD

**Issue by sf80** [MaxxRK/firstrade-api#43]
hi,
Previous versions of urls are connected properly,but not properly after changing api3x.firstrade.com

"statusCode":403,"error":"Forbidden","message":"Access denied"}
 # Get account data
----> 7 ft_accounts = account.FTAccountData(ft_ss)
      8 if len(ft_accounts.account_numbers) < 1:
      9     raise Exception("No accounts found or an error occured exiting...")

d:\ProgramData\Anaconda3\lib\site-packages\firstrade\account.py in __init__(self, session)
    296         response = self.session.get(urls.account_list())
    297         if response.status_code != 200 or response.json()["error"] != "":
--> 298             raise AccountResponseError(response.json()["error"])
    299         self.all_accounts = response.json()
    300         for item in self.all_accounts["items"]:

AccountResponseError: Failed to get account data. API returned the following error: Forbidden

**Comment by MaxxRK** [comment]
Were you using a profile? If so you need to make sure you delete the .pkl file. It will try and use the old cookies and they do not work.

**Comment by sf80** [comment]
I don't use cookies. I think the problem is using the new URL (https://api3x.firstrade.com/), which seems to be officially banned now. I suggest changing back to the original URL https://www.firstrade.com/

**Comment by MaxxRK** [comment]
It is not banned I use this almost everyday and it works fine.

**Comment by MaxxRK** [comment]
As there has been no reply to this in awhile closing.
