### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by PremGulrajani** [MaxxRK/firstrade-api#44]
line 5, in <module>
    need_code = ft_ss.login()
  line 129, in login
    need_code = self._handle_mfa()
  line 236, in _handle_mfa
    for item in self.otp_options:
TypeError: 'NoneType' object is not iterable

Unsure if i am doing something wrong, I am using the Quikstart

**Comment by MaxxRK** [comment]
What are you using for OTP? If it is not email then you will have to change the keyword from `email=` to the method you are using. I.E. `pin=`, `phone=`, `mfa_secret=` (The last one if using an authenticator)

**Comment by PremGulrajani** [comment]
You are right, my apologies, this worked!
