### ISSUE TITLE
Reporting successful even when it did not sell.

### ISSUE THREAD

**Issue by MaxxRK** [MaxxRK/firstrade-api#9]
firstrade is reporting successful even when it does not sell.

**Comment by Cfomodz** [comment]
I am new here, but having played with brokers before, I am guessing this is referring to a successful _order_ - as in with the notification from Robinhood when placing an order, "We've received your limit order to buy 1 share of XYZ through your Traditional IRA account at a maximum of $3.21 per share."

When placing a simple buy order via web the API will respond with a success -- Stating that _placing the order_ has been successful. You can then re-query the API after the fact with the order id (the browser does this automatically after I believe 1 second) to get its updated state of being filled or not.

But I will look into this more tomorrow when the market is open.

**Comment by MaxxRK** [comment]
I agree with these comments. I am going to close this issue. This will need a seperate query to check the status of an order.
